### ISSUE TITLE
MQTT Timeout

### ISSUE THREAD

**Issue by moku01** [NickStallman/home-assistant-repo#15] opened 2024-08-23 17:20 UTC
Hey, can somebody tell me whats wrong with my confic?

![2024-08-23 19_19_18-Home Assistant](https://github.com/user-attachments/assets/4aec2fce-3f35-44db-b73c-4042edcaf671)

 I'm always getting that error message... :(

**Comment by NickStallman** [comment] 2024-09-09 07:01
I've never seen that with my set up.

Can you tell me how you've configured MQTT? Where is it running?

**Comment by NickStallman** [comment] 2024-09-09 18:04
So just Mosquito MQTT as an addon? And MQTT Explorer on your PC connects fine?

What host/IP do you have configured in the MQTT connection string? Have you configured the Pi's IP just like how you connect with MQTT Explorer?

**Comment by moku01** [comment] 2024-09-13 08:08
Yes MQTT runs on the Pi, i can access ist via the HomeAssistant MQTT >Explorer Ad-On as well as the Desktop version. The Host IP is, as far as i know the Pi's IP Adress on port 1883

**Comment by NickStallman** [comment] 2024-09-18 20:42
I've done some googling and there's a few results with connack timeouts but nothing specific.

Is your MQTT server particularly busy and/or your Pi's CPU usage particularly high?
That's the only thing I can think of. Most search results seem to indicate high traffic on the MQTT side being the cause, rather than something specific this addon is doing.

**Comment by moku01** [comment] 2024-09-20 12:24
Thank you for your help, but the CPU is just used aroud 10% and no other Device uses MQTT. 
I'm gonna try to find a different solution.

**Comment by NickStallman** [comment] 2024-09-29 01:33
No worries. I'll close this issue as I'm not sure it's an issue with this addon specifically.

**Closed by NickStallman** 2024-09-29 01:33 UTC
