### ISSUE TITLE
Using  two Inverters, SG5 and SH5

### ISSUE THREAD

**Issue by dbuggz** [NickStallman/home-assistant-repo#13] opened 2024-07-26 07:25 UTC
Is there an option to use two inverters, or can I edit some .yaml?
regards
Dave

**Comment by NickStallman** [comment] 2024-09-12 21:38
Duplicate of https://github.com/NickStallman/home-assistant-repo/issues/9

I'd like to add multiple inverter support but I've been busy recently. :)

**Closed by NickStallman** 2024-09-12 21:38 UTC
